-- @block
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE categories;
TRUNCATE TABLE books;
TRUNCATE TABLE copies;
TRUNCATE TABLE clients;
TRUNCATE TABLE authors;
TRUNCATE TABLE rentals;
TRUNCATE TABLE publishers;
TRUNCATE TABLE books_authors;
SET FOREIGN_KEY_CHECKS = 1;